os: linux
dist: bionic
language: python
python:
  - "3.8"

cache:
  directories:
    - ${HOME}/.pio

env:
  global:
    #   - BUILDER_TOTAL_THREADS=4
    - BUILDER_TOTAL_THREADS=1
    - OWNER=${TRAVIS_REPO_SLUG%/*}
    - DEV=${OWNER/proddy/dev}
    - BRANCH=${TRAVIS_BRANCH/dev/}
    - TAG=${DEV}${BRANCH:+_}${BRANCH}

install:
  - env | grep TRAVIS
  - set -e
  - pip install -U platformio
  - pio platform update -p
  - set +e

branches:
  except:
    - /^travis-.*-build$/

script:
  - ./scripts/build.sh
# - ./scripts/build.sh -p

stages:
  - name: Release
#   if: type IN (cron, api)

jobs:
  include:
    - stage: Release
#     env: BUILDER_THREAD=0
#   - env: BUILDER_THREAD=1
#   - env: BUILDER_THREAD=2
#   - env: BUILDER_THREAD=3

before_deploy:
  - export FIRMWARE_VERSION=$(grep -E '^#define APP_VERSION' ./src/version.h | awk '{print $3}' | sed 's/"//g')
  - git tag -f travis-${TAG}-build
  - git remote add gh
    https://${OWNER}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push gh :travis-${TAG}-build || true
  - git push -f gh travis-${TAG}-build
  - git remote remove gh

deploy:
  provider: releases
  edge:
  #  source: wenkokke/dpl
    branch: master
  token: ${GITHUB_TOKEN}
  file_glob: true
  # file: "firmware/*.bin"
  file: "*.bin"
  name: latest development build
  release_notes:
    Version $FIRMWARE_VERSION.
    Automatic firmware builds of the current EMS-ESP branch built on $(date +'%F %T %Z') from commit $TRAVIS_COMMIT.
    Warning, this is a development build and not fully tested. Use at your own risk.
  cleanup: false
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    tags: false
    branch: dev

notifications:
  email:
    on_success: change
    on_failure: change

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/57e15f7798656d888194
    on_success: always
    on_failure: never
    on_start: never
