name: 'Pre-check on PR'
permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches: dev
    paths:
      - 'src/**'
      
jobs:
  pre-release:
    name: 'Automatic pre-release build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install PlatformIO
        run: |
          pip install wheel
          pip install -U platformio

      - name: Run unit tests
        run: |
          platformio run -e native-test -t exec
