name: 'pre-release'

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'

jobs:
  pre-release:
    name: 'Automatic pre-release build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Get EMS-ESP source code and version
        id: build_info
        run: |
          version=`grep -E '^#define EMSESP_APP_VERSION' ./src/version.h | awk -F'"' '{print $2}'`
          echo "VERSION=$version" >> $GITHUB_OUTPUT
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Build WebUI
        run: |
          cd interface
          yarn install
          yarn typesafe-i18n --no-watch
          sed -i "s/= 'pl'/= 'en'/" ./src/i18n/i18n-util.ts
          yarn build
          yarn webUI
      - name: Build 4M firmware
        run: |
          platformio run -e ci
      - name: Build S3 firmware
        run: |
          platformio run -e ci_s3
      - name: Build 16M firmware
        run: |
          platformio run -e ci_16M
      - name: Create GitHub Release
        id: 'automatic_releases'
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: Development Build v${{steps.build_info.outputs.VERSION}}
          automatic_release_tag: 'latest'
          prerelease: true
          files: |
            CHANGELOG_LATEST.md
            ./build/firmware/*.*
