name: 'Build test release'

on:
  workflow_dispatch:
  push:
    branches:
      - 'test'

permissions:
  contents: read

jobs:
  pre-release:
    name: 'Build Test Release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Install python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Enable Corepack
        run: corepack enable pnpm

      - name: Get the EMS-ESP version
        id: build_info
        run: |
          version=`grep -E '^#define EMSESP_APP_VERSION' ./src/emsesp_version.h | awk -F'"' '{print $2}'`
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          python -m pip install intelhex

      - name: Build webUI
        run: |
          platformio run -e build_webUI

      - name: Build modbus
        run: |
          platformio run -e build_modbus

      - name: Build standalone
        run: |
          platformio run -e build_standalone
          
      - name: Build all PIO target environments, from default_envs
        run: |
          platformio run

      - name: Create GitHub Release
        id: 'automatic_releases'
        uses: emsesp/action-automatic-releases@v1.0.0
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: Test Build v${{steps.build_info.outputs.VERSION}}
          automatic_release_tag: 'test'
          prerelease: true
          files: |
            CHANGELOG_LATEST.md
            ./build/firmware/*.*
            
